### ISSUE TITLE
How to set Java heap space for control m agent 

### ISSUE THREAD

**Issue by anshul07** [controlm/automation-api-community-solutions#95]
Hi, 

I am following the example **kubernetes-statefulset-agent-using-pvc** to run ctm on kuberntes. I am able to build the image but when I execute it I get java.lang.OutOfMemoryError. I believe I fix it increasing the heap size. Does someone know where can I set it up?

Here are the logs:

```
│ info:    Making SSL trust all certificates and all hostnames                                                                          │
│ info:    setting server to agent port: 7006                                                                                           │
│ info:    setting agent to server port: 7005                                                                                           │
│ info:    setting agent name (alias): statefulset-agent-0                                                                              │
│ info:    setting primary Control-M Server: 10.228.169.20                                                                              │
│ info:    setting authorized Control-M Server host                                                                                     │
│ info:    setting agent communication type to persistent                                                                               │
│ error:   Exception in thread "Exec Stream Pumper" java.lang.OutOfMemoryError: Java heap space                                         │
│     at java.base/java.util.Arrays.copyOf(Arrays.java:3745)                                                                            │
│     at java.base/java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:120)                                                   │
│     at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:95)                                          │
│     at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:156)                                                  │
│ error:                                                                                                                                │
│     at org.apache.commons.exec.StreamPumper.run(StreamPumper.java:108)                                                                │
│     at java.base/java.lang.Thread.run(Thread.java:834)                                                                                │

```

**Comment by codytrey** [comment]
Hi @anshul07 

Can you check if you have any resource limits/requests(either on the statefulset or as namespace/global defaults) affecting the amount of memory allocated to the pod?

I've not seen this error before, and that's the only thing I can think of that might be related. If you don't have any resource limits/requests set (or they're set reasonably high) I'd recommend you open a case with us on the BMC Support Central page so that we can gather logs and other environment data to review.

**Comment by anshul07** [comment]
Thanks @codytrey. I'll try those and will raise the support case :)
